# Definition of TLS certificates for joshiro.dev and joshiro.xyz domains using cert-manager
# with Cloudflare as the DNS provider. These certificates will be used by the
# Cilium Gateway to serve HTTPS traffic for the specified domains.
# --------------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-joshiro-dev
  namespace: default
spec:
  secretName: cert-joshiro-dev
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.joshiro.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-local-joshiro-dev
  namespace: default
spec:
  secretName: cert-local-joshiro-dev
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.local.joshiro.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-joshiro-xyz
  namespace: default
spec:
  secretName: cert-joshiro-xyz
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.joshiro.xyz"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-local-joshiro-xyz
  namespace: default
spec:
  secretName: cert-local-joshiro-xyz
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.local.joshiro.xyz"