# Namespace dedicated
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  labels:
    name: pihole
# Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Pi-hole Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: pihole
        image: pihole/pihole:2026.04.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/Mexico_City"
        - name: FTLCONF_webserver_api_password # Pihole v6 env variable for web password
          valueFrom:
            secretKeyRef:
              name: pihole-web-password
              key: password
        - name: FTLCONF_dns_listeningMode
          value: "all"
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        resources: # Resource requests and limits for the Pi-hole container
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN # Necesary if you use DHCP or IPv6 RA. If you only do DNS blocking you can remove it, but it doesn't hurt.
              - NET_BIND_SERVICE # To bind to privileged port 53. If you use a non-privileged port for DNS, you can remove this capability.
              - CHOWN
              - SETUID
              - SETGID
              - SYS_NICE
        livenessProbe:
          tcpSocket:
            port: dns-tcp
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: dns-tcp
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
          subPath: etc-pihole
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pihole-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web-svc
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
  - port: 80
    targetPort: 80
    name: web
---
# Router: Connects gateway (.23) to Pi-hole web service
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pihole-web-route
  namespace: pihole
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: main-gateway
    namespace: default
  hostnames:
  - "pihole.local.joshiro.xyz"
  rules:
  - backendRefs:
    - name: pihole-web-svc
      port: 80
---
# LoadBalancer Service: Exposes Pi-hole DNS service on port 53
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-svc
  namespace: pihole
  labels:
    io.cilium/needs-ip: "true"  # This label is required for Cilium to assign an IP to the LoadBalancer service
  annotations:
    io.cilium/lb-ipam-ips: "192.168.1.24" 
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp